apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-sakir
  labels:
    app: front-sakir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-sakir
  template:
    metadata:
      labels:
        app: front-sakir
    spec:
      imagePullSecrets:
        - name: mysecret
      containers:
        - name: front
          image: cloud.canister.io:5000/luke34/front:front
